dynaconf_merge = true

[default]
  testing = false

  # List of cluster storages.
  # If this param is setted, for all cluster name we bind
  # test account with specific storage.
  #
  # There is not binding for storage_name == 'DEFULT'.
  # Example:
  # cluster_storage_names = ['DEFAULT', 'Default cluster', 'Google Cloud Storage', 'S3 Cloud Storage', 'Azure Blob Storage']

  [default.api]
    storage_http_protocol = 'https'
    storage_port = '443'
    ws_timeout = 2
    upload_study_timeout = 200
    merge_timeout = 100

[testing]
  testing = true
  test_account_name = 'PYTHON_SDK_TEST_ACCOUNT'
  [testing.api]
    url = "https://local.ambrahealth.dev/api/v3"
    username = 'username'
    password = 'password'

[development]
  [development.api]
    url = "https://local.ambrahealth.dev/api/v3"
    username = 'username'
    password = 'password'
